[tox]
envlist =
    py311-dj42, py311-dj50, py311-dj51,
    py312-dj42, py312-dj50, py312-dj51, py312-dj52,
    py313-dj50, py313-dj51, py313-dj52
isolated_build = true

[testenv]
deps =
    pytest>=8
    pytest-django>=4.8
    pytest-mock>=3.12
    dj42: django~=4.2.0
    dj50: django~=5.0.0
    dj51: django~=5.1.0
    dj52: django~=5.2.0
commands =
    pytest tests/unit -v
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONPATH = {toxinidir}/src

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
